### ISSUE TITLE
Tokens Module

### ISSUE THREAD

**Issue by shaopengw** [laminar-protocol/open-runtime-module-library#4]
## Goal

Create a `orml-tokens` runtime module to support multiple types of token.

### Version 1 - Basic tokens functionalities

-  [x] Minimal `trait` abstraction `MultiCurrency`.
  - `transfer`
  - `mint`
  - `burn`
  - `slash`
- [x] Runtime module.
  - Impl `MultiCurrency`.
  - Dispatchable `transfer` extrinsic
- [x] Unit test.

### Version 2 - Compatibility with `srml-balance` module

- [x] Be compatible with `srml-balance` and `Currency`, which would be used for native token.

~~### Optional - Better issuance control via "imbalance"~~

~~- [ ] "imbalance" types represents `balance` change of tokens.~~
~~- [ ] Add imbalance types and rebalance feature to `MultiCurrency` and `orml-tokens`.~~

**Comment by xlc** [comment]
More things to be considered later:

- events
- error type
- weight / transaction fee
- existential deposits

**Comment by xlc** [comment]
I am also thinking about adding a `BaseCurrency` trait that is similar to `MultiCurrency` except it is for single currency.

We don't need all the advanced features of `Currency` most of the time. `BaseCurrency` is usually enough. This allow new implementation of `BaseCurrency` easy.
