### ISSUE TITLE
ExistentialDeposit for tokens module

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/open-runtime-module-library#70]
New constant `ExistentialDeposit`
New hook `On`

- Types
  - trait OnDustRemoval
    - fn on_dust_removal(amount: Balance)

- Trait
  - ExistentialDeposit: Get\<Balance>
    - Also a module constant
  - OnDustRemoval: OnDustRemoval

- Call
  - fn transfer_all(origin, dest: AccountId, currency_id: CurrencyId)
    - transfer all the remaining balances to given account

After account balances changed (transfer / withdraw / deposit), check if the remaining balance is lower than `ExistentialDeposit`. If it is lower, call `T::OnDustRemoval` and set the balance to zero.

**Comment by shaopengw** [comment]
> - ExistentialDeposit: Get<Balance>
>   - Also a module constant

A quick question: a runtime configurable `ExistentialDeposit` type in `Trait` sounds enough and flexible, what's the module constant for?

**Comment by shaopengw** [comment]
For the `transfer` function, might be better to return an error if balance of `to` is zero and `amount` is below existential deposit.

And the existential rule could also be applied to `slash`.

**Comment by xlc** [comment]
The behavior of transfer should be similar to pallet-balances module.
