### ISSUE TITLE
Why `Cargo.dev.toml`

### ISSUE THREAD

**Issue by JoshOrndorff** [laminar-protocol/open-runtime-module-library#71]
This is more a question for my own learning than an issue with the repo. Why is the file in the root called `Cargo.dev.toml` rather than `Cargo.toml`? Is it related to [cargo profiles](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections)?

Hope this question is welcome here. Thanks for the orml. I've learned a lot by watching it.

**Comment by xlc** [comment]
It is just a hack to workaround that Cargo does not support nested workspaces.

Currently ORML is been used by https://github.com/laminar-protocol/flowchain and https://github.com/AcalaNetwork/Acala. It is added as a submodule for the reason of ease of development.

The Cargo.toml file of acala/flowchain includes ORML modules as workspace members

https://github.com/laminar-protocol/flowchain/blob/7614fb12f92d22c9cb4dfda500382f6d373f9dc6/Cargo.toml#L62-L68

But for CI / standalone development purpose, ORML should have its own Cargo.toml workspace root file and hence Cargo.dev.toml. The makefile target will automatically copy it to Cargo.toml if needed.

https://github.com/laminar-protocol/open-runtime-module-library/blob/master/Makefile#L29-L30

Questions are welcome here. I will close this one. Feel free to reopen / post more questions as needed.
