### ISSUE TITLE
Vesting module: use `LockableCurrency` locks query when available

### ISSUE THREAD

**Issue by shaopengw** [laminar-protocol/open-runtime-module-library#78]
Currently there is no locks query functions in `LockableCurrency` trait, and `ensure_lockable` in vesting module is implemented via temp workarounds.

Once locks query available, in `ensure_lockable` function:
1. use locks query instead of `ensure_can_withdraw` for locks check.
2. remove `do_claim` workaround in `ensure_lockable` check, which keep locked amount query up to date.

Last but not least, `ensure_lockable` should not change state if failed, which is no guaranteed with `do_claim` workaround. Once locks query available, change all `assert_err!` to `assert_noop!` in `add_vesting_schedule` and `update_vesting_schedules` unit tests.

Blocked by Substrate [issue #4655](https://github.com/paritytech/substrate/issues/4655).

**Comment by xlc** [comment]
no needed anymore
